input.onGesture(Gesture.Shake, function () {
    basic.showString("Hello!")
    music._playDefaultBackground(music.builtInPlayableMelody(Melodies.Dadadadum), music.PlaybackMode.InBackground)
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Whole)), music.PlaybackMode.UntilDone)
    basic.showNumber(1)
    basic.pause(100)
    basic.showNumber(2)
    basic.pause(100)
    basic.showNumber(3)
    basic.pause(100)
    basic.showNumber(4)
    basic.pause(100)
    basic.showNumber(5)
    basic.pause(100)
    basic.showNumber(6)
    basic.pause(100)
    basic.showNumber(7)
    basic.pause(100)
    basic.showString("Good bye")
})
